##### user definable composition params #####

# probability of the composition acting on a highest metric (80 % chance of yes)
density = 80

# maximum number of audio files to be played (will only play one from each stream)
max_audio_playing = 4

# minimum duration for cello score onscreen (in seconds)
min_dur_cello_notation = 12

# maximum duraton for cello score onscreen (in seconds)
max_dur_cello_notation = 32

# duration of composition (in seconds)
duration_of_composition = 360


###### non-user variables ####

# the image generated by the random processes in visual.py
_image_to_display = " "

# dictonary of audio player status: name of pm: playing status,
_dict_of_playing = {"engagement": False,
                    "excitement": False,
                    "focus": False,
                    "interest": False,
                    "relaxation": False,
                    "stress": False
                    }

##### Emotiv access and app codes
# client secret = XS4I78088I9EFF4ToFlZIPl1uYctlYFBdJaL7e3cEDQSKdqjWFzZ0krVfLnUHpAPjvXtj4uk48kxTNcl4nUpMCorLjur90J26gYnsIHwAjitXqpcJe43xypWyaIOLOo5
# app name = digital_syzygies
# app ID = com.andrewhugill.digital_syzygies
# client Id = RUQh0lDR7AyecvvnsnlLaFimA8s7A2Vci1Uyd96X
# EEG = YES
